version: 2.1

jobs:
  build:
    machine:
      image: "windows-server-2019"
      resource_class: "windows.medium"
      shell: powershell.exe -ExecutionPolicy Bypass
      
    steps:
      - run:
          name: Install openJDK 15
          command: |
              $Env:ChocolateyUseWindowsCompression = 'true'
              choco install openjdk
                            
      - run:
          name: Check Java version
          command: |
              ls C:\"Program Files"\Openjdk
              Get-NetIPAddress




