version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Build image
          command: |
              docker build -t yaningo/buildtools2017:latest -m 8GB .
              
      - run:
          name: Push image
          command: |
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker push yaningo/buildtools2017:latest
              
      - run:
          name: Use executable container
          command: |
              docker run --rm yaningo/buildtools2017 C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\BuildTools\Common7\Tools\VsDevCmd.bat
              docker run --rm yaningo/buildtools2017 C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe -version
              docker run --rm yaningo/buildtools2017 MSBuild -version
              
