version: 2.1
  
jobs:
  build:
    docker:
      - image: circleci/python
      - image: mcr.microsoft.com/mssql/server:2017-CU22-ubuntu-16.04
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: totoIstiti
          MSSQL_MEMORY_LIMIT_MB: 3200
        command: ["/opt/mssql/bin/sqlservr", "-T7752"]
    resource_class: large
    steps:
      - run:
          command: |
            ACCEPT_EULA=y
            sudo sh -c 'curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -'
            sudo sh -c 'curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list'
            sudo apt-get update && sudo apt-get install mssql-tools -y
            echo ' export PATH="$PATH:/opt/mssql-tools/bin" >> BASH_ENV
            /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P totoIstiti -Q "CREATE DATABASE formstest COLLATE SQL_Latin1_General_CP1_CS_AS; DBCC tracestatus"
                            
workflows:
  populate:
    jobs:
      - build




