version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - run:
          name: Install build tools 2017
          command: |
              $Env:ChocolateyUseWindowsCompression = 'true'
              choco install visualstudio2017buildtools --package-parameters "--allWorkloads --includeRecommended --includeOptional"
              
      - run:
          name: Check MSBuild version
          #shell: cmd.exe
          command: |
              C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\BuildTools\Common7\Tools\VsDevCmd.bat -arch=amd64 -host_arch=amd64
              C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe -version
              setx /M PATH "$Env:PATH;C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\BuildTools\MSBuild\15.0\Bin"
              MSBuild.exe -version
