version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Build image
          command: |
              docker build -t buildtools2017:latest -m 4GB .
              
      - run:
          name: Use executable container
          command: |
              docker run --rm buildtools2017 msbuild -version
