version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - run: systeminfo
      - checkout              
      - run:
          #shell: cmd.exe
          name: Build image
          command: |
              docker build -t yaningo/buildtools2017:latest -m 8GB .
              
      - run:
          name: Log to DockerHub and push
          command: |
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              docker push yaningo/winstuff
              
      - run:
          name: Use executable container
          command: |
              docker run --rm buildtools2017 C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\BuildTools\Common7\Tools\VsDevCmd.bat
              docker run --rm buildtools2017 C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe -version
              docker run --rm buildtools2017 msbuild -version
