version: 2.1

orbs:
  win: circleci/windows@2.2.0
  
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/mssql/server:2017-CU22-ubuntu-16.04
        command: ["/opt/mssql/bin/mssql-conf traceflag 7752 on", "/opt/mssql/bin/sqlservr"]
    steps:
      - run:
          command: |
            sqlcmd -Slocalhost -Usa
                            
workflows:
  populate:
    jobs:
      - build




