version: 2.1

orbs:
  win: circleci/windows@2.2.0
  
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/mssql/server:2017-CU22-ubuntu-16.04
        command: ["/opt/mssql/bin/sqlservr", "/opt/mssql/bin/mssql-conf traceflag 7752 on"]
    steps:
      - run:
          command: |
            /opt/mssql/bin/mssql-conf traceflag 7752 on
                            
workflows:
  populate:
    jobs:
      - build




