version: 2.1

orbs:
  win: circleci/windows@2.2.0
  
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/mssql/server:2017-CU22-ubuntu-16.04
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: totoI
          MSSQL_MEMORY_LIMIT_MB: 3200
    resource_class: large
    steps:
      - run:
          command: |
            /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P totoI -Q "DBCC TRACEON (7752)"
                            
workflows:
  populate:
    jobs:
      - build




