version: 2.1

orbs:
  win: circleci/windows@2.2.0
  
jobs:
  build:
    executor:
      name: win/default
      shell: bash.exe

    steps:
      - run:
          command: |
            echo $env:DOCKER_USER
            echo ${DOCKER_USER}
            echo $DOCKER_USER
                            
workflows:
  populate:
    jobs:
      - build




