version: 2.1

jobs:
  build:
    machine:
      image: "windows-server-2019"
      resource_class: "windows.medium"
      shell: powershell.exe -ExecutionPolicy Bypass
      
    steps:
      - run:
          name: Install build tools 2017
          command: |
              $Env:ChocolateyUseWindowsCompression = 'true'
              choco install openjdk




