version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - run: systeminfo
      - checkout              
      - run:
          #shell: cmd.exe
          name: Build image
          command: |
              docker build -t yaningo/winstuff:buildtools2017 -m 8GB .
              
      - run:
          name: Use executable container
          command: |
              docker run --rm yaningo/winstuff:buildtools2017 C:\BuildTools\Common7\Tools\VsDevCmd.bat
              docker run --rm yaningo/winstuff:buildtools2017 msbuild -version
              
      - run:
          name: Push to DockerHub
          command: |
              docker push
