version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - run: systeminfo
      - checkout
      - run:
          command: |
              mkdir C:\BuildTools
              mkdir C:\TEMP
              cp Dockerfile C:\TEMP
              cd C:\TEMP
              
      - run:
          #shell: cmd.exe
          command: |
              docker build -t buildtools2017:latest -m 4GB .
