version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - run:
          name: Install build tools 2017
          command: |
              $Env:ChocolateyUseWindowsCompression = 'true'
              choco install -y visualstudio2017buildtools
              $Env:ROSLYN_COMPILER_LOCATION = 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Roslyn'
      - run:
          name: Check MSBuild version
          shell: cmd.exe
          command: |
              msbuild -version
              C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\BuildTools\Common7\Tools\VsDevCmd.bat
              C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe -version
